# Dotfiles scripts
alias upd="zsh ~/Documents/GitHub/dotfiles/update"
alias ins="zsh ~/Documents/GitHub/dotfiles/install"
alias bck="zsh ~/Documents/GitHub/dotfiles/backup"

# Paths
alias h="cd ~"
alias gh="cd ~/Documents/GitHub"
alias od="cd ~/OneDrive"
alias tui="cd ~/Documents/GitHub/tallui"

# Apps
alias ty="open -a typora"
alias vs="code ."

# Linux
alias l="ls -lAFh"
alias ll="ls -lFh" 
alias rm="rm -f"
alias rmd="rm -Rf"

# PHP
alias p="php"
alias stan="./vendor/bin/phpstan analyse"
alias stanp="../../vendor/bin/phpstan analyse"
alias pest="./vendor/bin/pest --coverage"
alias pestp="../../vendor/bin/pest --coverage"
alias pint="./vendor/bin/pint"
alias pintp="../../vendor/bin/pint"

# Node
alias no="npm outdated"
alias ni="npm install"
alias nu="npm update"
alias nb="npm run build"
alias nd="npm run dev"

# Laravel - https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/laravel
alias pa="php artisan"
alias pas="php artisan serve"
alias par="php artisan remote"
alias pam="php artisan migrate"
alias pamf="php artisan migrate:fresh"
alias pamfs="php artisan migrate:fresh --seed"
alias pamr="php artisan migrate:rollback"
alias pads="php artisan db:seed"
alias pamm="php artisan make:model"
alias pamc="php artisan make:controller"
alias pams="php artisan make:seeder"
alias pamt="php artisan make:test"
alias pamfa="php artisan make:factory"
alias pamp="php artisan make:policy"
alias pame="php artisan make:event"
alias pamj="php artisan make:job"
alias paml="php artisan make:listener"
alias pamn="php artisan make:notification"
alias pacac="php artisan cache:clear"
alias pacoc="php artisan config:clear"
alias pavic="php artisan view:clear"
alias paroc="php artisan route:clear"
alias paqf="php artisan queue:failed"
alias paqft="php artisan queue:failed-table"
alias paql="php artisan queue:listen"
alias paqr="php artisan queue:retry"
alias paqt="php artisan queue:table"
alias paqw="php artisan queue:work"

# Composer - https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/composer
alias c="composer"
alias cu="composer update"
alias cr="composer require"
alias ci="composer install"
alias cda="composer dump-autoload -o"

# Git - https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git
alias g="git"
alias ga="git add"
alias gaa="git add --all"
alias gapa="git add --patch"
alias gau="git add --update"
alias gav="git add --verbose"
alias gap="git apply"
alias gapt="git apply --3way"
alias gb="git branch"
alias gba="git branch --all"
alias gbd="git branch --delete"
alias gbda="git branch --no-color --merged | grep -vE "^([+]|\s($(git_main_branch)|$(git_develop_branch))\s*$)" | xargs git branch --delete 2>/dev/null"
alias gbD="git branch --delete --force"
alias gbl="git blame -b -w"
alias gbnm="git branch --no-merged"
alias gbr="git branch --remote"
alias gbs="git bisect"
alias gbsb="git bisect bad"
alias gbsg="git bisect good"
alias gbsr="git bisect reset"
alias gbss="git bisect start"
alias gc="git commit --verbose"
alias gc!="git commit --verbose --amend"
alias gcn!="git commit --verbose --no-edit --amend"
alias gca="git commit --verbose --all"
alias gca!="git commit --verbose --all --amend"
alias gcan!="git commit --verbose --all --no-edit --amend"
alias gcans!="git commit --verbose --all --signoff --no-edit --amend"
alias gcam="git commit --all --message"
alias gcas="git commit --all --signoff"
alias gcasm="git commit --all --signoff --message"
alias gcsm="git commit --signoff --message"
alias gcb="git checkout -b"
alias gcf="git config --list"
alias gcl="git clone --recurse-submodules"
alias gccd="git clone --recurse-submodules "$@" && cd "$(basename $_ .git)""
alias gclean="git clean --interactive -d"
alias gpristine="git reset --hard && git clean -dffx"
alias gcm="git checkout $(git_main_branch)"
alias gcd="git checkout $(git_develop_branch)"
alias gcmsg="git commit --message"
alias gco="git checkout"
alias gcor="git checkout --recurse-submodules"
alias gcount="git shortlog --summary -n"
alias gcp="git cherry-pick"
alias gcpa="git cherry-pick --abort"
alias gcpc="git cherry-pick --continue"
alias gcs="git commit -S"
alias gcss="git commit -S -s"
alias gcssm="git commit -S -s -m"
alias gd="git diff"
alias gdca="git diff --cached"
alias gdcw="git diff --cached --word-diff"
alias gdct="git describe --tags $(git rev-list --tags --max-count=1)"
alias gds="git diff --staged"
alias gdt="git diff-tree --no-commit-id --name-only -r"
alias gdnolock="git diff $@ ":(exclude)package-lock.json" ":(exclude)*.lock""
alias gdup="git diff @{upstream}"
alias gdv="git diff -w $@ | view -"
alias gdw="git diff --word-diff"
alias gf="git fetch"
alias gfa="git fetch --all --prune"
alias gfg="git ls-files | grep"
alias gfo="git fetch origin"
alias gg="git gui citool"
alias gga="git gui citool --amend"
alias ggf="git push --force origin $(current_branch)"
alias ggfl="git push --force-with-lease origin $(current_branch)"
alias ggl="git pull origin $(current_branch)"
alias ggp="git push origin $(current_branch)"
alias ggpnp="ggl && ggp"
alias ggpull="git pull origin "$(git_current_branch)""
alias ggpur="ggu"
alias ggpush="git push origin "$(git_current_branch)""
alias ggsup="git branch --set-upstream-to=origin/$(git_current_branch)"
alias ggu="git pull --rebase origin $(current_branch)"
alias gpsup="git push --set-upstream origin $(git_current_branch)"
alias gpsupf="git push --set-upstream origin $(git_current_branch) --force-with-lease"
alias ghh="git help"
alias gignore="git update-index --assume-unchanged"
alias gignored="git ls-files -v | grep "^[[:lower:]]""
alias git-svn-dcommit-push="git svn dcommit && git push github $(git_main_branch):svntrunk"
alias gk="gitk --all --branches &!"
alias gke="gitk --all $(git log --walk-reflogs --pretty=%h) &!"
alias gl="git pull"
alias glg="git log --stat"
alias glgp="git log --stat --patch"
alias glgg="git log --graph"
alias glgga="git log --graph --decorate --all"
alias glgm="git log --graph --max-count=10"
alias glo="git log --oneline --decorate"
alias glol="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'"
alias glols="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset' --stat"
alias glod="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'"
alias glods="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset' --date=short"
alias glola="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset' --all"
alias glog="git log --oneline --decorate --graph"
alias gloga="git log --oneline --decorate --graph --all"
alias glp="git log --pretty=<format>"
alias gm="git merge"
alias gmom="git merge origin/$(git_main_branch)"
alias gmtl="git mergetool --no-prompt"
alias gmtlvim="git mergetool --no-prompt --tool=vimdiff"
alias gmum="git merge upstream/$(git_main_branch)"
alias gma="git merge --abort"
alias gp="git push"
alias gpd="git push --dry-run"
alias gpf="git push --force-with-lease"
alias gpf!="git push --force"
alias gpoat="git push origin --all && git push origin --tags"
alias gpr="git pull --rebase"
alias gpu="git push upstream"
alias gpv="git push --verbose"
alias gr="git remote"
alias gra="git remote add"
alias grb="git rebase"
alias grba="git rebase --abort"
alias grbc="git rebase --continue"
alias grbd="git rebase $(git_develop_branch)"
alias grbi="git rebase --interactive"
alias grbm="git rebase $(git_main_branch)"
alias grbom="git rebase origin/$(git_main_branch)"
alias grbo="git rebase --onto"
alias grbs="git rebase --skip"
alias grev="git revert"
alias grh="git reset"
alias grhh="git reset --hard"
alias groh="git reset origin/$(git_current_branch) --hard"
alias grm="git rm"
alias grmc="git rm --cached"
alias grmv="git remote rename"
alias grrm="git remote remove"
alias grs="git restore"
alias grset="git remote set-url"
alias grss="git restore --source"
alias grst="git restore --staged"
alias grt="cd "$(git rev-parse --show-toplevel || echo .)""
alias gru="git reset --"
alias grup="git remote update"
alias grv="git remote --verbose"
alias gsb="git status --short -b"
alias gsd="git svn dcommit"
alias gsh="git show"
alias gsi="git submodule init"
alias gsps="git show --pretty=short --show-signature"
alias gsr="git svn rebase"
alias gss="git status --short"
alias gst="git status"
alias gsta="git stash push (git version >= 2.13)"
alias gsta="git stash save (git version < 2.13)"
alias gstaa="git stash apply"
alias gstc="git stash clear"
alias gstd="git stash drop"
alias gstl="git stash list"
alias gstp="git stash pop"
alias gsts="git stash show --text"
alias gstu="git stash --include-untracked"
alias gstall="git stash --all"
alias gsu="git submodule update"
alias gsw="git switch"
alias gswc="git switch -c"
alias gswm="git switch $(git_main_branch)"
alias gswd="git switch $(git_develop_branch)"
alias gts="git tag -s"
alias gtv="git tag | sort -V"
alias gtl="gtl(){ git tag --sort=-v:refname -n --list ${1}* }; noglob gtl"
alias gunignore="git update-index --no-assume-unchanged"
alias gunwip="git log --max-count=1 | grep -q -c "--wip--" && git reset HEAD~1"
alias gup="git pull --rebase"
alias gupv="git pull --rebase --verbose"
alias gupa="git pull --rebase --autostash"
alias gupav="git pull --rebase --autostash --verbose"
alias gupom="git pull --rebase origin $(git_main_branch)"
alias gupomi="git pull --rebase=interactive origin $(git_main_branch)"
alias glum="git pull upstream $(git_main_branch)"
alias gluc="git pull upstream $(git_current_branch)"
alias gwch="git whatchanged -p --abbrev-commit --pretty=medium"
alias gwip="git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign --message "--wip-- [skip ci]""
alias gam="git am"
alias gamc="git am --continue"
alias gams="git am --skip"
alias gama="git am --abort"
alias gamscp="git am --show-current-patch"
alias gwt="git worktree"
alias gwtls="git worktree list"
alias gwtmv="git worktree move"
alias gwtrm="git worktree remove"
