#!/bin.bash

echo ' '
echo ' '
echo '            _              _    _       '     
echo '           ( )            (_ ) (_ )  _  '
echo '   _ _    _| | _ __   _    | |  | | (_) '
echo ' / _  ) / _  |(  __)/ _ \  | |  | | | | '
echo '( (_| |( (_| || |  ( (_) ) | |  | | | | '
echo '`\__,_) \__,_)(_)   \___/ (___)(___)(_) '
echo ' '                                       
echo 'You are running the adrolli Mac backup.'
echo 'This will backup all config.'
echo 'and save it to iCloud.'
echo ' '

sudo -v
echo ' '

echo 'Create the backup folder'
echo '------------------------'
today=$(date +"%Y-%m-%d")
echo 'Backup to ~/Library/Mobile\ Documents/com~apple~CloudDocs/MacOS-Backup/'$today'/'
mkdir ~/Library/Mobile\ Documents/com~apple~CloudDocs/MacOS-Backup/${today}/
echo ' '

echo 'Create the latest link'
echo '----------------------'
rm -Rf ~/Library/Mobile\ Documents/com~apple~CloudDocs/MacOS-Backup/latest/
ln -s ~/Library/Mobile\ Documents/com~apple~CloudDocs/MacOS-Backup/${today}/ ~/Library/Mobile\ Documents/com~apple~CloudDocs/MacOS-Backup/latest
echo ' '

echo 'Backup MacOS Preferences'
echo '------------------------'
echo ' '
echo 'Backed up'
cp -Rfv ~/Library/Preferences ~/Library/Mobile\ Documents/com~apple~CloudDocs/MacOS-Backup/${today}/Preferences/ | wc -l
cp -Rfv ~/Documents/Obsidian\ Vault ~/Library/Mobile\ Documents/com~apple~CloudDocs/MacOS-Backup/${today}/Obsidian/ | wc -l
echo 'files'
echo ' '

open -g raycast://confetti