#!/bin.bash

echo ' '
echo ' '
echo '            _              _    _       '     
echo '           ( )            (_ ) (_ )  _  '
echo '   _ _    _| | _ __   _    | |  | | (_) '
echo ' / _  ) / _  |(  __)/ _ \  | |  | | | | '
echo '( (_| |( (_| || |  ( (_) ) | |  | | | | '
echo '`\__,_) \__,_)(_)   \___/ (___)(___)(_) '
echo ' '                                       
echo 'You are running the adrolli Mac installer.'
echo 'This will install many things.'
echo 'Use it at your own risk!'
echo ' '

sudo -v
echo ' '

touch $HOME/.hushlogin
echo ' '

echo 'Install Homebrew - https://brew.sh'
echo '----------------------------------'
NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
echo '# Set PATH, MANPATH, etc., for Homebrew.' >> /Users/alfdrollinger/.zprofile
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/alfdrollinger/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"
echo ' '

echo 'Install Oh My Zsh - https://ohmyz.sh'
echo '------------------------------------'
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
echo ' '

echo 'Install NodeJS - https://nodejs.org'
echo '----------------------------------'
brew install node
echo ' '

echo 'Install PHP - https://php.net'
echo '-----------------------------'
brew install php
echo ' '

echo 'Install Composer - https://getcomposer.org'
echo '------------------------------------------'
brew install composer
echo ' '

echo 'Install Laravel Herd - https://herd.laravel.com/'
echo '------------------------------------------------'
brew install --cask herd
echo ' '

echo 'Install Google Chrome - https://www.google.com/chrome'
echo '-----------------------------------------------------'
brew install --cask google-chrome
echo ' '

echo 'Install DBngin - https://dbngin.com'
echo '-----------------------------------'
brew install --cask dbngin
echo ' '

echo 'Install TablePlus - https://tableplus.com'
echo '-----------------------------------------'
brew install --cask tableplus
echo ' '

echo 'Install Visual Studio Code - https://code.visualstudio.com'
echo '----------------------------------------------------------'
brew install --cask visual-studio-code
echo ' '

echo 'Install Typora - https://typora.io'
echo '----------------------------------'
brew install --cask typora
echo ' '

echo 'Install Github Desktop - https://desktop.github.com'
echo '---------------------------------------------------'
brew install --cask github
echo ' '

echo 'Install iTerm2 - https://iterm2.com'
echo '-----------------------------------'
brew install --cask iterm2
echo ' '

echo 'Install Slack - https://slack.com'
echo '----------------------------------------'
brew install --cask slack
echo ' '

echo 'Install The Fuck - https://github.com/nvbn/thefuck'
echo '--------------------------------------------------'
brew install --cask thefuck
echo ' '

echo 'Install Teamviewer - https://www.teamviewer.com'
echo '--------------------------------------------------'
brew install --cask teamviewer
echo ' '

echo 'Install Docker - https://www.docker.com'
echo '----------------------------------------'
brew install --cask docker
echo ' '

echo 'Install Firefox - https://www.mozilla.org'
echo '-----------------------------------------'
brew install --cask firefox
echo ' '

echo 'Install Microsoft Teams - https://www.microsoft.com/microsoft-teams/'
echo '--------------------------------------------------------------------'
brew install --cask microsoft-teams
echo ' '

echo 'Install Raycast - https://www.raycast.com/'
echo '------------------------------------------'
brew install --cask raycast
echo ' '

echo 'Install Microsoft Edge - https://www.microsoft.com/edge'
echo '-------------------------------------------------------'
brew install --cask microsoft-edge
echo ' '

echo 'Install Ray from Spatie - https://www.myray.app'
echo '-----------------------------------------------'
brew install --cask ray
echo ' '

echo 'Install Tinkerwell from BeyondCode - https://www.tinkerwell.app'
echo '---------------------------------------------------------------'
brew install --cask tinkerwell
echo ' '

echo 'Install Helo from BeyondCode - https://usehelo.com'
echo '--------------------------------------------------'
brew install --cask helo
echo ' '

echo 'Install Invoker from BeyondCode - https://invoker.dev'
echo '-----------------------------------------------------'
brew install --cask invoker
echo ' '

echo 'Install Bunch - https://bunchapp.co/'
echo '------------------------------------'
brew install --cask bunch
echo ' '

echo 'Install Tunnelblick  - https://tunnelblick.net'
echo '----------------------------------------------'
brew install --cask tunnelblick
echo ' '

echo 'Install Forklift - https://binarynights.com/'
echo '--------------------------------------------'
brew install --cask forklift
echo ' '

echo 'Install GoodSync - https://goodsync.com/'
echo '----------------------------------------'
brew install --cask goodsync
echo ' '

echo 'Install Forklift - https://www.macbartender.com/'
echo '------------------------------------------------'
brew install --cask bartender
echo ' '

echo 'Install 1password - https://1password.com'
echo '-----------------------------------------'
brew install --cask 1password
echo ' '

echo 'Install 1password CLI - https://1password.com/de/downloads/command-line'
echo '-----------------------------------------------------------------------'
brew install --cask 1password-cli
echo ' '

echo 'Install Spotify - https://spotify.com'
echo '-------------------------------------'
brew install --cask spotify
echo ' '

echo 'Install Fontbase - https://fontba.se'
echo '------------------------------------'
brew install --cask fontbase
echo ' '

echo 'Install Fontbase - https://formulae.brew.sh/formula/mysql-client'
echo '----------------------------------------------------------------'
brew install --cask mysql-client
export PATH=$PATH:/opt/homebrew/opt/mysql-client/bin
echo ' '

echo 'Install Obsidian - https://obsidian.md'
echo '--------------------------------------'
brew install --cask obsidian
echo ' '

echo 'Install Onyx - https://www.titanium-software.fr/en/onyx.html'
echo '------------------------------------------------------------'
brew install --cask onyx
echo ' '

echo 'Install Postman - https://www.postman.com/'
echo '------------------------------------------'
brew install --cask postman
echo ' '

echo 'Install Raindrop - https://raindrop.io/'
echo '---------------------------------------'
brew install --cask raindropio
echo ' '

echo 'Install Snagit - https://www.techsmith.com/screen-capture.html'
echo '--------------------------------------------------------------'
brew install --cask snagit
echo ' '

echo 'Install Webex - https://www.webex.com'
echo '------------------------------------'
brew install --cask webex-meetings
echo ' '

echo 'Install Redis - https://redis.com'
echo '---------------------------------'
brew install redis
redis-cli ping
echo ' '
echo 'Type redis-server to start Redis'
echo ' '

echo 'Install Lulu - https://objective-see.com/products/lulu.html'
echo '-----------------------------------------------------------'
brew install --cask lulu
echo ' '

echo 'Install AdGuard - https://adguard.com/'
echo '--------------------------------------'
brew install adguard
echo ' '

echo 'Install Powerline Font - https://inspirnathan.com/posts/22-install-ohmyzsh-with-agnoster-theme/'
echo '-----------------------------------------------------------------------------------------------'
git clone https://github.com/powerline/fonts.git
cd fonts
./install.sh
cd .. && rm -rf fonts
echo ' '

echo 'Copy Aliases'
echo '------------'
cp ~/Documents/GitHub/adrolli/dotfiles/aliases.zsh ~/.oh-my-zsh/custom
echo ' '

echo 'Copy Git config'
echo '---------------'
cp ~/GitHub/dotfiles/.gitconfig ~/.gitconfig
echo ' '

echo 'Copy .zshrc'
echo '-----------'
cp ~/GitHub/dotfiles/.zshrc ~/
echo ' '

echo 'Restore config from iCloud'
echo '--------------------------'
cp -Rfv ~/Library/Mobile\ Documents/com~apple~CloudDocs/MacOS-Backup/latest/Preferences/ ~/Library/Preferences | wc -l
echo 'files restored'
echo ' '

echo 'Copy the tui script'
echo '-------------------'
cp ~/GitHub/dotfiles/tui ~/tui
echo ' '

open -g raycast://confetti
