#!/bin.bash

echo ' '
echo ' '
echo '            _              _    _       '     
echo '           ( )            (_ ) (_ )  _  '
echo '   _ _    _| | _ __   _    | |  | | (_) '
echo ' / _  ) / _  |(  __)/ _ \  | |  | | | | '
echo '( (_| |( (_| || |  ( (_) ) | |  | | | | '
echo '`\__,_) \__,_)(_)   \___/ (___)(___)(_) '
echo ' '                                       
echo 'You are running the adrolli Mac updater.'
echo 'This will update many things.'
echo 'Use it at your own risk!'
echo ' '

sudo -v
echo ' '

echo 'Stop services'
echo '-------------'
brew services stop php
sudo brew services stop nginx
sudo brew services stop dnsmasq
echo ' '

echo 'Self-update Homebrew'
echo '--------------------'
brew update
echo ' '

echo 'Update all casks and formulas'
echo '-----------------------------'
brew upgrade
echo ' '

echo 'Anything outdated?'
echo '------------------'
brew outdated 
echo ' '

echo 'Cleanup Homebrew'
echo '----------------'
brew cleanup
echo ' '

echo 'List all things homebrewn'
echo '-------------------------'
brew list
echo ' '

echo 'Start services'
echo '--------------'
brew services start php
sudo brew services start nginx
sudo brew services start dnsmasq
echo ' '

echo 'Update Laravel Valet'
echo '--------------------'
composer global require laravel/valet
valet install
echo ' '

echo 'Update Aliases'
echo '--------------'
cp ~/Documents/GitHub/adrolli/dotfiles/aliases.zsh ~/.oh-my-zsh/custom
echo ' '

echo 'Update Git config'
echo '-----------------'
cp ~/Documents/GitHub/adrolli/dotfiles/.gitconfig ~/.gitconfig
echo ' '

echo 'Update .zshrc'
echo '-------------'
cp ~/Documents/GitHub/adrolli/dotfiles/.zshrc ~/
echo ' '

echo 'Update the tui script'
echo '----------------------'
cp ~/Documents/GitHub/adrolli/dotfiles/tui ~/tui
echo ' '

echo 'Mac Updates? Install using softwareupdate -i [NAME]'
echo '---------------------------------------------------'
softwareupdate -l
echo ' '

open -g raycast://confetti